<a href="https://colab.research.google.com/github/Pradip-ai/Analysis-of-P-l-over-Market-performance/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamentals concept of Tensorflow

- Introduction to tensor
- getting info from tensors
- Manipulating tensors
- Tensors and NumPy
- Using @tf.function
- Using GPUs with TF or TPUs
- Exercise



Introduction to Tensors


In [2]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)


2.15.0


In [3]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check no of dimension of Tf
scalar.ndim

0

In [5]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#check the dim of Vector
vector.ndim

1

In [12]:
#create a matrix
matrix = tf.constant([[10, 7], [7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [13]:
matrix.ndim


2

In [18]:
#create another matrix
another_matrix = tf.constant([[10., 7], [3., 2.], [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [19]:
another_matrix.ndim

2

In [20]:
#Lets create a tensor
tensor = tf.constant([[[1, 2, 3], [2, 3, 4], [3, 4, 5]]])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]]], dtype=int32)>

In [21]:
tensor.ndim

3

In [22]:
# Scalar : Single Number
#Vector : a number with direction (Eg: Wind Dpeed & Direcrion)
# Matrix : a 2 D array of numbers
#Tensor: a n d array of numbers ( n can be 1, 2, 3, ....)




In [26]:
# Create a tensor with 'tf.variable'
c = tf.Variable([10, 7])
u = tf.constant([10, 7])
c, u


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [35]:
#hcange the one of the elements in c


c[0].assign(50)
c

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([50,  7], dtype=int32)>

In [37]:
u[0].assign(100)
u

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [44]:
# Creating random tensors

#Random Tensors are tensors  of some abitrary size which cintain random numbers

# Create two random ( but the same tensors)

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape =(3, 2))
random_1



<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [46]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))
random_2


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [47]:
random_1, random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [53]:
# Shuffle the tensor ( Shuffle the data)


# Create a tensor with values from 0 to 9
not_shuffled = tf.constant([1, 2, 3, 4, 5,])

tf.random.shuffle(not_shuffled)
not_shuffled




<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>